CREATE TABLE "raw"."shopify_orders" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"data_upload_batch_id" uuid NOT NULL,
	"row_number" integer NOT NULL,
	"name" text,
	"email" text,
	"financial_status" text,
	"paid_at" text,
	"fulfillment_status" text,
	"fulfilled_at" text,
	"accepts_marketing" text,
	"currency" text,
	"subtotal" text,
	"shipping" text,
	"taxes" text,
	"total" text,
	"discount_code" text,
	"discount_amount" text,
	"shipping_method" text,
	"order_created_at" text,
	"lineitem_quantity" text,
	"lineitem_name" text,
	"lineitem_price" text,
	"lineitem_compare_at_price" text,
	"lineitem_sku" text,
	"lineitem_requires_shipping" text,
	"lineitem_taxable" text,
	"lineitem_fulfillment_status" text,
	"billing_name" text,
	"billing_street" text,
	"billing_address1" text,
	"billing_address2" text,
	"billing_company" text,
	"billing_city" text,
	"billing_zip" text,
	"billing_province" text,
	"billing_country" text,
	"billing_phone" text,
	"shipping_name" text,
	"shipping_street" text,
	"shipping_address1" text,
	"shipping_address2" text,
	"shipping_company" text,
	"shipping_city" text,
	"shipping_zip" text,
	"shipping_province" text,
	"shipping_country" text,
	"shipping_phone" text,
	"notes" text,
	"note_attributes" text,
	"cancelled_at" text,
	"payment_method" text,
	"payment_reference" text,
	"refunded_amount" text,
	"vendor" text,
	"outstanding_balance" text,
	"employee" text,
	"location" text,
	"device_id" text,
	"shopify_order_id" text,
	"tags" text,
	"risk_level" text,
	"source" text,
	"lineitem_discount" text,
	"tax_1_name" text,
	"tax_1_value" text,
	"tax_2_name" text,
	"tax_2_value" text,
	"tax_3_name" text,
	"tax_3_value" text,
	"tax_4_name" text,
	"tax_4_value" text,
	"tax_5_name" text,
	"tax_5_value" text,
	"phone" text,
	"receipt_number" text,
	"duties" text,
	"billing_province_name" text,
	"shipping_province_name" text,
	"payment_id" text,
	"payment_terms_name" text,
	"next_payment_due_at" text,
	"payment_references" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "raw"."shopify_orders" ADD CONSTRAINT "shopify_orders_tenant_id_tenants_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "raw"."shopify_orders" ADD CONSTRAINT "shopify_orders_data_upload_batch_id_data_upload_batches_id_fk" FOREIGN KEY ("data_upload_batch_id") REFERENCES "public"."data_upload_batches"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "raw_shopify_orders_batch_row_idx" ON "raw"."shopify_orders" USING btree ("data_upload_batch_id","row_number");--> statement-breakpoint
CREATE INDEX "raw_shopify_orders_tenant_idx" ON "raw"."shopify_orders" USING btree ("tenant_id");