import {
  pgSchema,
  uuid,
  jsonb,
  integer,
  timestamp,
  index,
  text,
  bigint,
} from "drizzle-orm/pg-core";

import {
  dataUploadBatches,
  dataUploadStatusEnum,
  tenants,
} from "./reconciliation.ts";

const raw = pgSchema("raw");

export const rawOrders = raw.table(
  "orders",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id").notNull().references(() => tenants.id, {
      onDelete: "cascade",
      name: "orders_tenant_id_tenants_id_fk",
    }),
    dataUploadBatchId: uuid("data_upload_batch_id")
      .notNull()
      .references(() => dataUploadBatches.id, {
        onDelete: "cascade",
        name: "orders_data_upload_batch_id_data_upload_batches_id_fk",
      }),
    rowNumber: integer("row_number").notNull(),
    payload: jsonb("payload").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    batchRowIdx: index("raw_orders_batch_row_idx").on(
      table.dataUploadBatchId,
      table.rowNumber,
    ),
  }),
);

export const rawShopifyOrders = raw.table(
  "shopify_orders",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tenantId: uuid("tenant_id").notNull().references(() => tenants.id, {
      onDelete: "cascade",
      name: "shopify_orders_tenant_id_tenants_id_fk",
    }),
    dataUploadBatchId: uuid("data_upload_batch_id")
      .notNull()
      .references(() => dataUploadBatches.id, {
        onDelete: "cascade",
        name: "shopify_orders_data_upload_batch_id_data_upload_batches_id_fk",
      }),
    rowNumber: integer("row_number").notNull(),
    name: text("name"),
    email: text("email"),
    financialStatus: text("financial_status"),
    paidAt: text("paid_at"),
    fulfillmentStatus: text("fulfillment_status"),
    fulfilledAt: text("fulfilled_at"),
    acceptsMarketing: text("accepts_marketing"),
    currency: text("currency"),
    subtotal: text("subtotal"),
    shipping: text("shipping"),
    taxes: text("taxes"),
    total: text("total"),
    discountCode: text("discount_code"),
    discountAmount: text("discount_amount"),
    shippingMethod: text("shipping_method"),
    orderCreatedAt: text("order_created_at"),
    lineitemQuantity: text("lineitem_quantity"),
    lineitemName: text("lineitem_name"),
    lineitemPrice: text("lineitem_price"),
    lineitemCompareAtPrice: text("lineitem_compare_at_price"),
    lineitemSku: text("lineitem_sku"),
    lineitemRequiresShipping: text("lineitem_requires_shipping"),
    lineitemTaxable: text("lineitem_taxable"),
    lineitemFulfillmentStatus: text("lineitem_fulfillment_status"),
    billingName: text("billing_name"),
    billingStreet: text("billing_street"),
    billingAddress1: text("billing_address1"),
    billingAddress2: text("billing_address2"),
    billingCompany: text("billing_company"),
    billingCity: text("billing_city"),
    billingZip: text("billing_zip"),
    billingProvince: text("billing_province"),
    billingCountry: text("billing_country"),
    billingPhone: text("billing_phone"),
    shippingName: text("shipping_name"),
    shippingStreet: text("shipping_street"),
    shippingAddress1: text("shipping_address1"),
    shippingAddress2: text("shipping_address2"),
    shippingCompany: text("shipping_company"),
    shippingCity: text("shipping_city"),
    shippingZip: text("shipping_zip"),
    shippingProvince: text("shipping_province"),
    shippingCountry: text("shipping_country"),
    shippingPhone: text("shipping_phone"),
    notes: text("notes"),
    noteAttributes: text("note_attributes"),
    cancelledAt: text("cancelled_at"),
    paymentMethod: text("payment_method"),
    paymentReference: text("payment_reference"),
    refundedAmount: text("refunded_amount"),
    vendor: text("vendor"),
    outstandingBalance: text("outstanding_balance"),
    employee: text("employee"),
    location: text("location"),
    deviceId: text("device_id"),
    shopifyOrderId: text("shopify_order_id"),
    tags: text("tags"),
    riskLevel: text("risk_level"),
    source: text("source"),
    lineitemDiscount: text("lineitem_discount"),
    tax1Name: text("tax_1_name"),
    tax1Value: text("tax_1_value"),
    tax2Name: text("tax_2_name"),
    tax2Value: text("tax_2_value"),
    tax3Name: text("tax_3_name"),
    tax3Value: text("tax_3_value"),
    tax4Name: text("tax_4_name"),
    tax4Value: text("tax_4_value"),
    tax5Name: text("tax_5_name"),
    tax5Value: text("tax_5_value"),
    phone: text("phone"),
    receiptNumber: text("receipt_number"),
    duties: text("duties"),
    billingProvinceName: text("billing_province_name"),
    shippingProvinceName: text("shipping_province_name"),
    paymentId: text("payment_id"),
    paymentTermsName: text("payment_terms_name"),
    nextPaymentDueAt: text("next_payment_due_at"),
    paymentReferences: text("payment_references"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    batchRowIdx: index("raw_shopify_orders_batch_row_idx").on(
      table.dataUploadBatchId,
      table.rowNumber,
    ),
    tenantIdx: index("raw_shopify_orders_tenant_idx").on(table.tenantId),
  }),
);

export const rawOrdersProcessingLogs = raw.table("orders_processing_logs", {
  dataUploadBatchId: uuid("data_upload_batch_id"),
  tenantId: uuid("tenant_id"),
  rowsLoaded: bigint("rows_loaded", { mode: "number" }),
  reportedRowCount: integer("reported_row_count"),
  status: dataUploadStatusEnum("status"),
  processingStartedAt: timestamp("processing_started_at", { withTimezone: true }),
  processingCompletedAt: timestamp("processing_completed_at", { withTimezone: true }),
  lastRowCreatedAt: timestamp("last_row_created_at", { withTimezone: true }),
  processedAt: timestamp("processed_at", { withTimezone: true }),
  dbtInvocationId: text("dbt_invocation_id"),
  triggeredBy: text("triggered_by"),
   errorMessage: text("error_message").default("none"),
  additionalInfo: jsonb("additional_info").$default(null),
});
